"use client";
import { useMemo, useState } from "react";
import { drafts } from "./data";
import { CareerIcon } from "./icons";

type DraftKind = keyof typeof drafts;
type Message = { type: "ai" | "user"; text: string };

function revisedDocument(kind: DraftKind, prompt: string) {
  const p = prompt.toLowerCase();
  if (kind === "cv") {
    if (p.includes("engineering")) return `<h1>Alex Morgan</h1><p class="career-contact-line">Frontend Engineer · alex@example.com · GitHub: github.com/alex · New York</p><h2>Professional Summary</h2><p>Frontend engineer specializing in React, TypeScript, accessible UI, and scalable design systems.</p><h2>Experience</h2><p><strong>Frontend Engineer · Northstar Labs</strong></p><ul><li>Built React dashboards used by 40k+ monthly users.</li><li>Improved core web vitals by 38% through code splitting and rendering optimization.</li><li>Created shared components adopted by three product teams.</li></ul><h2>Skills</h2><p>React · TypeScript · Accessibility · Testing · GraphQL · Performance</p>`;
    if (p.includes("data")) return `<h1>Alex Morgan</h1><p class="career-contact-line">Data Analyst · alex@example.com · Tableau: alexdata · Remote</p><h2>Professional Summary</h2><p>Data analyst with 5+ years translating raw data into dashboards, forecasting models, and decision-ready narratives.</p><h2>Experience</h2><p><strong>Data Analyst · BrightMetrics</strong></p><ul><li>Cut weekly reporting time from 6 hours to 45 minutes.</li><li>Built churn analysis that informed a 9% reduction in churn.</li><li>Defined trustworthy metrics with finance, marketing, and operations.</li></ul><h2>Skills</h2><p>SQL · Python · Tableau · Forecasting · Experiment analysis</p>`;
    if (p.includes("keyword")) return `${drafts.cv.html}<h2>Targeted Keywords</h2><p>Product strategy · UX research · Figma · Design systems · Accessibility · SaaS onboarding · Experimentation</p>`;
    if (p.includes("metric") || p.includes("bullet")) return drafts.cv.html.replace("</ul>", "<li>Translated user research into prioritized improvements, increasing task completion by 18%.</li></ul>");
    if (p.includes("concise")) return drafts.cv.html.replace("Product designer with 6+ years creating intuitive SaaS workflows, leading discovery, and translating complex user needs into polished interfaces.", "Product-minded designer with 6+ years shipping measurable SaaS improvements across onboarding, accessibility, research, and design systems.");
    return drafts.cv.html;
  }
  if (p.includes("direct")) return `<h1>Cover Letter Draft</h1><p class="career-contact-line">Alex Morgan · alex@example.com · July 2026</p><p>Dear Hiring Manager,</p><p>I am applying for the Frontend Engineer role because my experience aligns closely with your needs in React, TypeScript, design systems, and accessible product development.</p><p>At Northstar Labs, I built production dashboards, improved performance by 38%, and created shared components adopted across multiple teams.</p><p>I would appreciate the opportunity to discuss how I can contribute.</p><p>Best regards,<br>Alex Morgan</p>`;
  if (p.includes("analytical")) return `<h1>Cover Letter Draft</h1><p class="career-contact-line">Alex Morgan · alex@example.com · July 2026</p><p>Dear Hiring Team,</p><p>I am interested in the Data Analyst role because it combines SQL analysis, clear dashboards, forecasting, and practical recommendations.</p><p>I have automated reporting, built churn analyses, and partnered with stakeholders to define metrics teams could trust.</p><p>Thank you for your consideration.</p><p>Sincerely,<br>Alex Morgan</p>`;
  if (p.includes("short") || p.includes("180")) return `<h1>Cover Letter Draft</h1><p class="career-contact-line">Alex Morgan · alex@example.com · July 2026</p><p>Dear Hiring Team,</p><p>I am excited to apply. My background combines user research, product design, and cross-functional delivery, including a 22% activation improvement and a design system that accelerated shipping.</p><p>I enjoy simplifying complex AI workflows into clear, useful experiences and would welcome the chance to bring that craft to your team.</p><p>Sincerely,<br>Alex Morgan</p>`;
  if (p.includes("warm")) return drafts.cover.html.replace("I am excited to apply for the Product Designer role. Your focus on practical AI tools stood out because my best work sits at the intersection of clear workflows, user empathy, and measurable product outcomes.", "I was genuinely drawn to this role because your team builds practical tools that help people work with more clarity. My strongest work comes from listening carefully and turning user insight into polished experiences.");
  if (p.includes("opening")) return drafts.cover.html.replace("I am excited to apply for the Product Designer role. Your focus on practical AI tools stood out because my best work sits at the intersection of clear workflows, user empathy, and measurable product outcomes.", "This role immediately stood out because it combines three areas where I do my best work: understanding user behavior, shaping simple AI-assisted workflows, and translating ambiguity into products people can use confidently.");
  return drafts.cover.html;
}

export function DraftStudioPage() {
  const [kind, setKind] = useState<DraftKind>("cv");
  const draft = drafts[kind];
  const [html, setHtml] = useState<string>(draft.html);
  const [text, setText] = useState("");
  const [messages, setMessages] = useState<Message[]>([{ type: "ai", text: "I can revise this CV directly. Choose a quick edit or type a specific instruction." }]);
  const suggestions = useMemo(() => draft.suggestions, [draft]);
  function switchKind(next: DraftKind) { setKind(next); setHtml(drafts[next].html); setMessages([{ type: "ai", text: `I can revise this ${next === "cv" ? "CV" : "cover letter"}. Choose a quick edit or type a specific instruction.` }]); }
  function apply(prompt: string) { if (!prompt.trim()) return; setMessages((items) => [...items, { type: "user", text: prompt }, { type: "ai", text: `Applied that edit to the ${kind === "cv" ? "CV" : "cover letter"} preview. Backend AI generation is not wired yet, so this uses local template revisions.` }]); setHtml(revisedDocument(kind, prompt)); setText(""); }
  return <><section className="career-page-banner career-container"><h1 className="career-page-title">CV & Cover Letter AI drafts</h1><p className="career-lede small">Select a document, edit the live preview on the left, then use the AI chat to revise tone, keywords, bullets, and role fit.</p><div className="career-doc-switch"><button className={`career-doc-tab ${kind === "cv" ? "active" : ""}`} type="button" onClick={() => switchKind("cv")}>CV Draft</button><button className={`career-doc-tab ${kind === "cover" ? "active" : ""}`} type="button" onClick={() => switchKind("cover")}>Cover Letter</button></div></section><section className="career-studio career-container"><article className="career-panel"><div className="career-panel-bar"><h2>{draft.title}</h2><div className="career-tools">{draft.tools.map((tool) => <button className="career-tool" type="button" onClick={() => apply(`Use a ${tool.toLowerCase()} template`)} key={tool}>{tool}</button>)}</div></div><div className="career-document" contentEditable suppressContentEditableWarning spellCheck dangerouslySetInnerHTML={{ __html: html }} /></article><aside className="career-panel career-chat"><div className="career-panel-bar"><h2>AI Editor</h2><span className="career-tag">{draft.mode}</span></div><div className="career-chat-body">{messages.map((message, index) => <div className={`career-message ${message.type}`} key={`${message.type}-${index}`}>{message.text}</div>)}<div className="career-suggestions">{suggestions.map((suggestion) => <button type="button" onClick={() => apply(suggestion)} key={suggestion}>{suggestion}</button>)}</div></div><div className="career-compose"><label className="sr-only" htmlFor="career-chat-text">Ask AI to edit this draft</label><textarea id="career-chat-text" value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) apply(text); }} placeholder="Ask AI to edit this draft…" /><button className="career-btn" type="button" onClick={() => apply(text)}><CareerIcon name="send" />Apply AI Edit</button></div></aside></section></>;
}
