import type { Application, DiscoverFilters, Interview, JourneyRole, JourneyState, JourneyStatus } from "./types";
export const statusLabels: Record<JourneyStatus,string>={discovered:"Discovered",shortlisted:"Shortlisted",applying:"Applying",submitted:"Submitted",interviewing:"Interviewing",offer:"Offer",accepted:"Accepted",closed:"Closed"};
export function getRoleById(s:JourneyState,id:string){return s.roles.find(r=>r.id===id)}
export function getApplicationById(s:JourneyState,id:string){return s.applications.find(a=>a.id===id)}
export function getApplicationByRoleId(s:JourneyState,roleId:string){return s.applications.find(a=>a.roleId===roleId)}
export function getInterviewById(s:JourneyState,id:string){return s.interviews.find(i=>i.id===id)}
export function getInterviewByRoleId(s:JourneyState,roleId:string){return s.interviews.find(i=>i.roleId===roleId)}
export function getRolesByStatus(s:JourneyState,status:JourneyStatus){return s.roles.filter(r=>r.status===status&&!r.dismissed)}
export function getPipelineCounts(s:JourneyState){return s.roles.reduce((a,r)=>({...a,[r.status]:(a[r.status]??0)+(!r.dismissed?1:0)}),{} as Record<JourneyStatus,number>)}
export function getNextAction(status:JourneyStatus){return ({discovered:"View role",shortlisted:"Start application",applying:"Continue application",submitted:"Add update / Prepare follow-up",interviewing:"Continue preparation",offer:"Review offer",accepted:"View outcome",closed:"Review learning / Archive"} as Record<JourneyStatus,string>)[status]}
export function filterAndSortRoles(roles:JourneyRole[], f:DiscoverFilters){let out=roles.filter(r=>!r.dismissed); if(f.query) out=out.filter(r=>`${r.title} ${r.company} ${r.tags.join(" ")}`.toLowerCase().includes(f.query.toLowerCase())); if(f.workStyle!=="All") out=out.filter(r=>r.workStyle===f.workStyle); if(f.level!=="All") out=out.filter(r=>r.level.toLowerCase().includes(f.level.toLowerCase())); if(f.match!=="All") out=out.filter(r=>r.matchScore>=Number(f.match)); if(f.savedOnly) out=out.filter(r=>r.status==="shortlisted"); return [...out].sort((a,b)=> f.sort==="match"?b.matchScore-a.matchScore:f.sort==="deadline"?(a.closingDate??"9999").localeCompare(b.closingDate??"9999"):a.posted.localeCompare(b.posted));}
export function calculateApplicationProgress(a:Application){const checks=Object.values(a.preflight).filter(Boolean).length; const total=Object.keys(a.preflight).length||1; const docs=(a.artifacts.cv?1:0)+(a.artifacts.cover?1:0); return Math.min(100, Math.round(((docs/2)*40+(checks/total)*40+(a.status==="submitted"?20:0))));}
export function calculateInterviewReadiness(i:Interview){let score=0; if(i.checklist.requirements) score+=20; if(i.selectedStories.length>=2) score+=25; else if(i.selectedStories.length) score+=10; if(Object.values(i.practiceAnswers).some(Boolean)) score+=20; if(i.checklist.company) score+=20; if(i.questionsToAsk.length) score+=15; return Math.min(100,score)}
const daysUntil=(iso:string)=>Math.ceil((new Date(iso).getTime()-new Date("2026-07-10T00:00:00Z").getTime())/86400000);
export function getHighestPriorityAction(s:JourneyState){const urgent=s.interviews.find(i=>!i.completed&&daysUntil(i.when)<=7&&calculateInterviewReadiness(i)<80); if(urgent) return {kind:"interview", href:`/interviews/${urgent.id}`, label:"Continue preparation", role:getRoleById(s,urgent.roleId)}; const app=s.applications.find(a=>a.status==="applying"&&calculateApplicationProgress(a)<100); if(app) return {kind:"application",href:`/applications/${app.id}`,label:"Continue application",role:getRoleById(s,app.roleId)}; const sub=s.applications.find(a=>a.status==="submitted"); if(sub) return {kind:"followup",href:`/applications/${sub.id}`,label:"Prepare follow-up",role:getRoleById(s,sub.roleId)}; const short=s.roles.find(r=>r.status==="shortlisted"&&r.closingDate); if(short) return {kind:"shortlist",href:`/jobs/${short.id}`,label:"Review shortlisted role",role:short}; const disc=[...s.roles].filter(r=>r.status==="discovered"&&!r.dismissed).sort((a,b)=>b.matchScore-a.matchScore)[0]; return disc?{kind:"discover",href:`/jobs/${disc.id}`,label:"View best match",role:disc}:undefined;}
