"use client";
import { useEffect, useRef } from "react";
import { useJourney } from "../journey/JourneyProvider";
import { statusLabels } from "../journey/selectors";
import type { JourneyAction, JourneyStatus } from "../journey/types";
export function StatusBadge({status}:{status:JourneyStatus}){return <span className={`cj-badge ${status}`}>● {statusLabels[status]}</span>}
export function Progress({value,label}:{value:number;label:string}){return <div className="cj-progress"><div className="cj-progress-label"><span>{label}</span><strong>{value}%</strong></div><progress value={value} max={100}>{value}%</progress></div>}
export function EmptyState({title,body,action}:{title:string;body:string;action?:React.ReactNode}){return <section className="cj-empty"><h2>{title}</h2><p>{body}</p>{action}</section>}
export function Skeleton(){return <div className="cj-skeleton" aria-hidden="true" />}
export function ToastRegion(){const {state,dispatch}=useJourney(); return <div className="cj-toasts" role="status" aria-live="polite">{state.toasts.slice(-3).map(t=><div className="cj-toast" key={t.id}><span>{t.message}</span>{t.action&&<button type="button" onClick={()=>{dispatch(t.action as JourneyAction);dispatch({type:"dismissToast",id:t.id})}}>{t.actionLabel}</button>}<button type="button" aria-label="Dismiss message" onClick={()=>dispatch({type:"dismissToast",id:t.id})}>×</button></div>)}</div>}
export function ConfirmDialog({open,title,description,onConfirm,onCancel,confirmLabel="Confirm"}:{open:boolean;title:string;description:string;onConfirm:()=>void;onCancel:()=>void;confirmLabel?:string}){const ref=useRef<HTMLDivElement>(null); useEffect(()=>{if(open) ref.current?.querySelector<HTMLButtonElement>("button")?.focus(); const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape") onCancel()}; if(open) document.addEventListener("keydown",onKey); return()=>document.removeEventListener("keydown",onKey)},[open,onCancel]); if(!open) return null; return <div className="cj-dialog-backdrop" role="presentation"><div className="cj-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" aria-describedby="dialog-desc" ref={ref}><h2 id="dialog-title">{title}</h2><p id="dialog-desc">{description}</p><div className="cj-actions"><button className="career-btn ghost" type="button" onClick={onCancel}>Cancel</button><button className="career-btn" type="button" onClick={onConfirm}>{confirmLabel}</button></div></div></div>}
